[package]
name = "screenrecorder-rs"
version = "0.1.0"
edition = "2024"

[build]
rustflags = ["-C", "target-cpu=native"]

[profile.release]
opt-level = 3
lto = "fat"            # Ottimizza l'inlining tra diverse crate (inclusi i binding C)
codegen-units = 1      # Genera codice binario più compatto e veloce
panic = "abort"        # Rimuove le tabelle di unwinding

[dependencies]
apple-cf = "0.10.0"
bytes = "1.12.1"
crossbeam-channel = "0.5.17"
mp4 = "0.14.0"
openh264 = "0.9.8"
scap = "0.0.8"
screencapturekit-sys = "0.2.8"
videotoolbox = { version = "0.20.0", features = ["async"] }
yuvutils-rs = "0.4"
